Stable year and prev
fire2a/growth pull request #8
Opened 2024-12-10 00:28 UTC by antoniochavez18

Se actualiza Readme, se prepara para caso de que pueda funcionar con datos reales, se modifica el calc_biomass para que tenga año estable (con grafico de 1_id) y se agrega prev para poder simular rodales ya raleados desde un inicio,

2024-12-11 15:46 UTC, antoniochavez18 commented on simulator.py
que rid ahora sea r significa que va del 0,1,2... o que tiene los fid de la tabla?

2024-12-12 16:13 UTC, fdobad requested changes
change:
1. id to model id, or mid
2. fid should be the first column

2024-12-12 16:13 UTC, fdobad commented on README.md
> +- **fid**: File ID of the `.csv` or `.shp` file
why id and fid ?
can it be simplified?

2024-12-19 19:48 UTC, fdobad requested changes
ortografia

2024-12-19 19:48 UTC, fdobad commented on README.md
> +### example of new formula of biomass in model whit id 30
whit

2024-12-19 19:48 UTC, fdobad commented on README.md
> +    min_ral = 6 #minimun age where you can thinn a tree
![image](https://github.com/user-attachments/assets/8a292e93-b786-40b0-b9c1-bd9be522e3f2)
# lower bound to tree thinning actions

2024-12-26 18:44 UTC, fdobad approved these changes

2024-12-26 18:45 UTC, merged